services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128MB
      restart_policy:
        condition: on-failure